version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: POSTGRES_DB_Infinity_Vision
    environment:
      POSTGRES_DB: InfinityVisionDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: . # Image has to be built from Dockerfile located in this directory
    container_name: WEB_Infinity_Vision
    command: ["/app/InfinityVision/entrypoint.sh"]
    volumes: # Mounting local directory with a directory inside container
      - .:/app/InfinityVision
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
