version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: POSTGRES_DB_Infinity_Vision
    environment:
      POSTGRES_DB: koyebdb
      POSTGRES_USER: koyeb-adm
      POSTGRES_PASSWORD: S2ch4kVWjKFR
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build:
      context: . # Image has to be built from Dockerfile located in this directory
      dockerfile: Dockerfile
    image: infinityvision:latest
    env_file:
      - .env
    container_name: WEB_Infinity_Vision
    command: ["/app/InfinityVision/entrypoint.sh"]
    volumes: # Mounting local directory with a directory inside container
      - .:/app/InfinityVision
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
