# Generated by Django 5.1 on 2024-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
